timelineData =
[
  {
    "left_shift": "0.2",
    "date_coord": "-4600000000",
    "name": "Formation of the Sun",
    "theme": "Environment",
    "dates": "4.6 billion years ago",
    "location": "Orion Spur, Milky Way",
    "description": "The Sun is a 4.5 billion-year-old yellow dwarf star – a hot glowing ball of hydrogen and helium – at the center of our solar system. It’s about 93 million miles (150 million kilometers) from Earth and it’s our solar system’s only star. Without the Sun’s energy, life as we know it could not exist on our home planet.\n\nFrom our vantage point on Earth, the Sun may appear like an unchanging source of light and heat in the sky. But the Sun is a dynamic star, constantly changing and sending energy out into space. The science of studying the Sun and its influence throughout the solar system is called heliophysics.",
    "src1": "https://solarsystem.nasa.gov/solar-system/sun/in-depth/#otp_formation",
    "src2": "",
    "image1src": "https://solarsystem.nasa.gov/system/feature_items/images/806_Sun_Features_Coronal_Holes-800x600.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "0.25",
    "date_coord": "-4500000000",
    "name": "Formation of the Earth and Moon",
    "theme": "Environment",
    "dates": "4.5 billion years ago",
    "location": "",
    "description": "",
    "src1": "https://solarsystem.nasa.gov/planets/earth/in-depth/#otp_formation",
    "src2": "https://marketbusinessnews.com/earth-made-of-two-planets-so-is-moon/122684/",
    "image1src": "https://i0.wp.com/marketbusinessnews.com/wp-content/uploads/2016/01/Earth-and-Moon-rocks-have-same-chemical-signatures.jpg?w=800&ssl=1",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "0.27",
    "date_coord": "-4000000000",
    "name": "Origins of water",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "Any water on Earth during the latter part of its accretion would have been disrupted by the Moon-forming impact (~4.5 billion years ago), which likely vaporized much of Earth's crust and upper mantle and created a rock-vapor atmosphere around the young planet. The rock vapor would have condensed within two thousand years, leaving behind hot volatiles which probably resulted in a majority carbon dioxide atmosphere with hydrogen and water vapor. Afterwards, liquid water oceans may have existed despite the surface temperature of 230 °C (446 °F) due to the increased atmospheric pressure of the CO2 atmosphere. As cooling continued, most CO2 was removed from the atmosphere by subduction and dissolution in ocean water, but levels oscillated wildly as new surface and mantle cycles appeared.",
    "src1": "https://en.wikipedia.org/wiki/Origin_of_water_on_Earth",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Water_molecule_%281%29.svg/440px-Water_molecule_%281%29.svg.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "0.3",
    "date_coord": "-4000000000",
    "name": "Precambrian - Archean",
    "theme": "Environment",
    "dates": "4000 – 2500 Ma",
    "location": "",
    "description": "In this time, the Earth's crust had cooled enough for continents to form and for the earliest known life to start. Life was simple throughout the Archean, mostly represented by shallow-water microbial mats called stromatolites, and the atmosphere lacked free oxygen.",
    "src1": "https://en.wikipedia.org/wiki/Archean",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Archean.png/500px-Archean.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "0.35",
    "date_coord": "-4000000000",
    "name": "Single cell life",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "0.38",
    "date_coord": "-3500000000",
    "name": "Earliest free oxygen",
    "theme": "Environment",
    "dates": "3.5 billion years ago",
    "location": "",
    "description": "O2 build-up in the Earth's atmosphere. Red and green lines represent the range of the estimates while time is measured in billions of years ago (Ga).\nStage 1 (3.85–2.45 Ga): Practically no O2 in the atmosphere.\nStage 2 (2.45–1.85 Ga): O2 produced, but absorbed in oceans and seabed rock.\nStage 3 (1.85–0.85 Ga): O2 starts to gas out of the oceans, but is absorbed by land surfaces and formation of ozone layer.\nStages 4 and 5 (0.85 Ga–present): O2 sinks filled, the gas accumulates.",
    "src1": "https://en.wikipedia.org/wiki/Geological_history_of_oxygen",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Oxygenation-atm-2.svg/2880px-Oxygenation-atm-2.svg.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-3400000000",
    "name": "Stromatolites from Archaean rocks",
    "theme": "Environment",
    "dates": "3.4 billion years ago",
    "location": "Western Australia are",
    "description": "Although a claim in 2017 says that the oldest fossils come from rocks found in Canada, the stromatolites from Archaean rocks in Western Australia are widely accepted as the oldest-known fossils with strong evidence. Stromatolite fossils are distinctive and look like layered rock formation. They were formed by ancient blue-green algae known as cyanobacteria and the oldest stromatolites are estimated to be about 3.5 billion years old. 3,480 million years ago have been found in western Australia",
    "src1": "https://en.wikipedia.org/wiki/Stromatolite",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Stromatolithe_Pal%C3%A9oarch%C3%A9en_-_MNHT.PAL.2009.10.1.jpg/440px-Stromatolithe_Pal%C3%A9oarch%C3%A9en_-_MNHT.PAL.2009.10.1.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2500000000",
    "name": "Precambrian - Proterozoic",
    "theme": "Environment",
    "dates": "2500 to 538.8 million years ago",
    "location": "",
    "description": "The Proterozoic covers the time from the appearance of oxygen in Earth's atmosphere to just before the proliferation of complex life (such as trilobites or corals) on the Earth. The name Proterozoic combines two forms of ultimately Greek origin: protero- meaning 'former, earlier', and -zoic, 'of life'.",
    "src1": "https://en.wikipedia.org/wiki/Proterozoic",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Proterozoic_collage.png/500px-Proterozoic_collage.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2400000000",
    "name": "Great Oxidation Event",
    "theme": "Environment",
    "dates": "2.4 billion years ago",
    "location": "",
    "description": "Earth's atmosphere and the shallow ocean first experienced a rise in the amount of oxygen.",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-630000000",
    "name": "Multicellular life",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-630000000",
    "name": "Fungi",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-630000000",
    "name": "Plants",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-630000000",
    "name": "Animals",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-600000000",
    "name": "Multicellular organism fossil",
    "theme": "Environment",
    "dates": "600 million years ago",
    "location": "",
    "description": "A fossil of a 600 million-year-old multicellular organism displays unexpected evidence of complexity. Credit: Virginia Tech",
    "src1": "https://vtx.vt.edu/articles/2014/09/092514-science-cellfossil.html",
    "src2": "",
    "image1src": "https://vtx.vt.edu/content/dam/vtx_vt_edu/articles/2014/09/images/092514-science-cellfossil.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-400000000",
    "name": "Oldest Known Fungus",
    "theme": "Environment",
    "dates": "400 million years ago",
    "location": "",
    "description": "Fossil dating from the Silurian period of the Palaeozoic era, about 440 million years ago, is not only the oldest example of a fossilized fungus, but is also the oldest fossil of any terrestrial organism yet found.",
    "src1": "https://www.sci.news/paleontology/oldest-known-fungus-tortotubus-protuberans-03672.html",
    "src2": "https://www.oldest.org/animals/fossils/",
    "image1src": "https://cdn.sci.news/images/2016/03/image_3672_2-Tortotubus-protuberans.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "First vertebrates",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "First mammals",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "Earliest primates",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "Earliest apes",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "Gorilla split",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "Chimpanzee split",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "Earliest bipedal",
    "theme": "Environment",
    "dates": "?",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-330000000",
    "name": "Earliest stone tools",
    "theme": "Technology",
    "dates": "3.3 million years ago",
    "location": "Lake Turkana in Kenya",
    "description": "They were unearthed from the shores of Lake Turkana in Kenya, and date to 3.3 million years ago.\n\nThey are 700,000 years older than any tools found before, even pre-dating the earliest humans in the Homo genus.",
    "src1": "https://www.bbc.com/news/science-environment-32804177",
    "src2": "",
    "image1src": "https://ichef.bbci.co.uk/news/976/mcs/media/images/83115000/jpg/_83115944_untitledcutattempt.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2310000",
    "name": "Homo Habilis",
    "theme": "Environment",
    "dates": "2.31 million years ago to 1.65 million",
    "location": "East Africa",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/8/80/KNM_ER_1813_%28H._habilis%29.png",
    "image1": "",
    "image2src": "https://upload.wikimedia.org/wikipedia/en/timeline/ov250pq1nytg6nmm8w4y0vfdt3xsvte.png",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2000000",
    "name": "Homo Erectus",
    "theme": "Environment",
    "dates": "Earliest occurrence about 2 million years ago.",
    "location": "East Africa",
    "description": "",
    "src1": "https://en.wikipedia.org/wiki/Homo_erectus",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-1700000",
    "name": "Earliest fire in Africa",
    "theme": "Environment",
    "dates": "1.7 to 2.0 million years ago",
    "location": "East Africa",
    "description": "Claims for the earliest definitive evidence of control of fire by a member of Homo range from 1.7 to 2.0 million years ago.\nEvidence for the \"microscopic traces of wood ash\" as controlled use of fire by Homo erectus, beginning roughly 1 million years ago, has wide scholarly support.",
    "src1": "https://en.wikipedia.org/wiki/Control_of_fire_by_early_humans",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-800000",
    "name": "Earliest fire in Europe",
    "theme": "Environment",
    "dates": "800,000 years",
    "location": "Spain",
    "description": "Prehumans living around 800,000 years ago in what’s now southeastern Spain were, literally, trailblazers. They lit small, controlled blazes in a cave, a new study finds. Shallow ripples caused by heating run across a piece of rock excavated in a Spanish cave. \nThis and other finds indicate that an undetermined Homo species lit small fires in the cave around 800,000 years ago, researchers say.  Each square on the measuring stick covers 1 centimeter.",
    "src1": "https://www.sciencenews.org/article/earliest-evidence-fire-making-europe-found",
    "src2": "",
    "image1src": "https://www.sciencenews.org/wp-content/uploads/2016/06/053116_bb_early-fire-inline_free.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-300000",
    "name": "Homo Sapiens",
    "theme": "Environment",
    "dates": "between 200,000 and 300,000",
    "location": "East Africa",
    "description": "Homo sapiens, the first modern humans, evolved from their early hominid predecessors between 200,000 and 300,000 years ago. They developed a capacity for language about 50,000 years ago.\nThe first modern humans began moving outside of Africa starting about 70,000-100,000 years ago.\nHumans are the only known species to have successfully populated, adapted to, and significantly altered a wide variety of land regions across the world, resulting in profound historical and environmental impacts.",
    "src1": "https://www.khanacademy.org/humanities/world-history/world-history-beginnings/origin-humans-early-societies/a/where-did-humans-come-from",
    "src2": "https://en.wikipedia.org/wiki/Human",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Spreading_homo_sapiens_la.svg/640px-Spreading_homo_sapiens_la.svg.png",
    "image1": "",
    "image2src": "https://i.pinimg.com/originals/ba/17/8e/ba178ec5b3dca4f4afde4baa0446dcf7.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-155000",
    "name": "Mitochondrial Eve",
    "theme": "Environment",
    "dates": "155,000 years ago",
    "location": "East Africa",
    "description": "In human genetics, the Mitochondrial Eve (also mt-Eve, mt-MRCA) is the matrilineal most recent common ancestor (MRCA) of all living humans. In other words, she is defined as the most recent woman from whom all living humans descend in an unbroken line purely through their mothers and through the mothers of those mothers, back until all lines converge on one woman.",
    "src1": "https://en.wikipedia.org/wiki/Mitochondrial_Eve",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Early_diversification.PNG",
    "image1": "",
    "image2src": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/MtDNA-MRCA-generations-Evolution.svg/2560px-MtDNA-MRCA-generations-Evolution.svg.png",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-75000",
    "name": "Shells Beads",
    "theme": "Money",
    "dates": "75,000 B.P.",
    "location": "Blombos Cave, South Africa,",
    "description": "Beads made from shells of the pea-sized snail Nassarius kraussianus, that lived in a nearby estuary.",
    "src1": "https://nakamotoinstitute.org/shelling-out/",
    "src2": "",
    "image1src": "https://nakamotoinstitute.org/static/img/docs/shelling-out/blombosbeads2.gif",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-73000",
    "name": "Oldest known drawing by human hands",
    "theme": "Language",
    "dates": "73,000 B.P.",
    "location": "Blombos Cave, South Africa,",
    "description": "Claimed \"Oldest known drawing by human hands\". Estimated to be 73,000 years old and possible rock art",
    "src1": "https://en.wikipedia.org/wiki/Blombos_Cave#Earliest_known_rock_drawing",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Claimed_Oldest_Known_Drawing_by_Human_Hands_Discovered_in_South_African_Cave.jpg",
    "image1": "",
    "image2src": "https://upload.wikimedia.org/wikipedia/commons/4/4a/Blombo.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-40000",
    "name": "Ostrich-eggshell beads",
    "theme": "Money",
    "dates": "40,000 B.P.",
    "location": "Kenya Rift Valley",
    "description": "In the late 1990s archaeologist Stanley Ambrose discovered, in a rock-shelter in the Rift Valley of Kenya, a cache of beads made of ostrich eggshell, blanks, and shell fragments. They are dated using the argon-argon (40Ar/39Ar) ratio to at least 40,000 years old.",
    "src1": "https://nakamotoinstitute.org/shelling-out/",
    "src2": "",
    "image1src": "https://nakamotoinstitute.org/static/img/docs/shelling-out/beads.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "38",
    "date_coord": "-35000",
    "name": "Lebombo bone",
    "theme": "Language",
    "dates": "35000 BCE",
    "location": "Eswatini, Lebombo Mountains",
    "description": "The Lebombo bone is a bone tool made of a baboon fibula with incised markings discovered in the Lebombo Mountains located between South Africa and Eswatini. Changes in the section of the notches indicate the use of different cutting edges, which the bone's discoverer, Peter Beaumont, views as evidence for their having been made, like other markings found all over the world, during participation in rituals.\nThe bone is between 44,200 and 43,000 years old, according to 24 radiocarbon datings. This is far older than the Ishango bone with which it is sometimes confused. Other notched bones are 80,000 years old but it is unclear if the notches are merely decorative or if they bear a functional meaning.\nAccording to The Universal Book of Mathematics the Lebombo bone's 29 notches suggest \"it may have been used as a lunar phase counter, in which case African women may have been the first mathematicians, because keeping track of menstrual cycles requires a lunar calendar\". However, the bone is clearly broken at one end, so the 29 notches may or may not be the total number. In the cases of other notched bones since found globally, there has been no consistent notch tally, many being in the 1–10 range.",
    "src1": "https://en.wikipedia.org/wiki/Lebombo_bone",
    "src2": "https://historyofinformation.com/detail.php?id=1976",
    "image1src": "https://historyofinformation.com/images/Screen_Shot_2021-02-17_at_11.37.11_AM_big.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "38",
    "date_coord": "-35000",
    "name": "Venus of Hohle Fels",
    "theme": "Language",
    "dates": "30-40,000 years before present",
    "location": "Schelklingen, Baden-Württemberg, Germany",
    "description": "The Earliest Known Examples of Figurative Art",
    "src1": "https://www.historyofinformation.com/detail.php?entryid=1789",
    "src2": "",
    "image1src": "https://historyofinformation.com/images/Screen_Shot_2020-08-20_at_11.49.03_AM.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-29000",
    "name": "Venus of Dolní Věstonice",
    "theme": "Language",
    "dates": "",
    "location": "in the modern-day Czech Republic",
    "description": "Earliest-known ceramic objects: Gravettian figurine",
    "src1": "https://www.realmofhistory.com/2017/09/01/venus-of-dolni-vestonice-oldest-ceramic-artifact/",
    "src2": "",
    "image1src": "https://www.realmofhistory.com/wp-content/uploads/2017/09/venus-of-dolni-vestonice-oldest-ceramic-artifact_4.jpg?ezimgfmt=ng%3Awebp%2Fngcb20%2Frs%3Adevice%2Frscb20-1",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-28000",
    "name": "Necklace from a burial",
    "theme": "Money",
    "dates": "28,000 BP.",
    "location": "Sungir, Russia",
    "description": "Interlocking and interchangeable beads. Each mammoth ivory bead may have required one to two hours of labor to manufacture",
    "src1": "https://nakamotoinstitute.org/shelling-out/",
    "src2": "",
    "image1src": "https://nakamotoinstitute.org/static/img/docs/shelling-out/beadsdetail.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-27000",
    "name": "Wolf bone",
    "theme": "Language",
    "dates": "25 to 28,000 years old",
    "location": "Czechoslovakia,",
    "description": "In 1937, an 18 cm-long radial wolf bone was  discovered at Věstonice in the Czech Republic and dated to 30,000 years ago. Karel Absolon presented it in The Illustrated London News (1937), pointing out that it had fifty-five notches incised on it. First came 25 in groups of five, then a notch of double length, followed by a similar double notch that began a series of 30. This would prove the mammoth hunters ability to count. It was thought that the groups of five were suggested by the five fingers of a hand.",
    "src1": "https://kartsci.org/kocomu/computer-history/history-abacus-ancient-computing/",
    "src2": "",
    "image1src": "https://kartsci.org/wp-content/uploads/2018/12/wolf-bone-tally-smbw.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-27000",
    "name": "Stencil of human hand",
    "theme": "Language",
    "dates": "27,000 years B.P.",
    "location": "Cosquer Cave, France",
    "description": "Hand stencils now total 65, the highest number in Europe except for Gargas (Hautes-Pyrénées) and possibly El Castillo in Spain. They are all located in the east side of the chamber, with one in the south. None is in the west. Right at the brink of a 57 feet deep vertical shaft – a location which in itself is significant - they are all black. On other panels, they may be black or red. One positive red hand has been found. A number of hand stencils have been scratched or painted over with dots and bars.",
    "src1": "https://en.wikipedia.org/wiki/Cosquer_Cave",
    "src2": "",
    "image1src": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.c1C7-pryCUZ6-p579J810gHaE8%26pid%3DApi&f=1&ipt=688418408384c6b542dc0929a3d619421f418ddd6aa408bf0898287c432c2b1e&ipo=images",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-25300",
    "name": "Stone slab drawings",
    "theme": "Language",
    "dates": "c.25,500 - 25,300 years ago.",
    "location": "Apollo 11 Cave in Namibia",
    "description": "The cave contained some of the oldest pieces of mobile art ever discovered in southern Africa, associated with charcoal that was radiocarbon dated from 27,500 to 25,500 BP.",
    "src1": "https://en.wikipedia.org/wiki/Apollo_11_Cave",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Apollo-11_stone_slab.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-17000",
    "name": "Lascaux decorated cave",
    "theme": "Language",
    "dates": "17,000 years old.",
    "location": "France, Vézère Valley",
    "description": "The cave contains nearly 6,000 figures, which can be grouped into three main categories: animals, human figures, and abstract signs. The paintings contain no images of the surrounding landscape or the vegetation of the time.",
    "src1": "https://en.wikipedia.org/wiki/Lascaux#Images",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Lascaux_painting.jpg",
    "image1": "",
    "image2src": "https://d.ibtimes.co.uk/en/full/1495897/lascaux-iv.webp?w=736&f=e80fdba938e015b1c8306c6c119cca98",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-15000",
    "name": "Fragments of pots, Xianrendong cave",
    "theme": "Language",
    "dates": "20,000 - 10.000 BC",
    "location": "China",
    "description": "Possible oldest potery",
    "src1": "https://en.wikipedia.org/wiki/Xianren_Cave",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/7/75/Xianrendong_Cave_Pottery_-_2.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-14800",
    "name": "Winnemucca Lake petroglyphs",
    "theme": "Language",
    "dates": "14,800 – 10,500 years",
    "location": "Nixon, Nevada, United States",
    "description": "North America's Earliest Rock Art",
    "src1": "https://en.wikipedia.org/wiki/Winnemucca_Lake",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/DSCN0858.JPG/640px-DSCN0858.JPG",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-14000",
    "name": "Mammoth Ivory Map",
    "theme": "Language",
    "dates": "14,000 BC",
    "location": "Ukraine",
    "description": "oldest known map in the world",
    "src1": "https://donsmaps.com/mammothcamp.html",
    "src2": "",
    "image1src": "https://www.donsmaps.com/images28/mezhirichmap.jpg",
    "image1": "",
    "image2src": "https://files.abovetopsecret.com/files/img/ef5414ccfc.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-10000",
    "name": "Bhimbetka rock art",
    "theme": "Language",
    "dates": "10,000 years old",
    "location": "India",
    "description": "The rock shelters and caves of Bhimbetka have a large number of paintings. The oldest paintings are found to be 10,000 years old, but some of the geometric figures date to as recently as the medieval period.",
    "src1": "https://en.wikipedia.org/wiki/Bhimbetka_rock_shelters",
    "src2": "https://www.indiadivine.org/bhimbetka-caves-inhabited-100000-years/",
    "image1src": "https://www.indiadivine.org/wp-content/uploads/2016/08/bhimbetka-06.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-10000",
    "name": "Magura Cave",
    "theme": "Language",
    "dates": "~10.000 and 8.000 years",
    "location": "Bulgaria",
    "description": "The drawings represent important events of the society that had occupied the Magura Cave: religious ceremonies, hunting scenes and depictions of deities which are unique on the Balkan peninsula. The Fertility Dance and the Hunting Ceremony rank among the most noteworthy paintings.",
    "src1": "https://en.wikipedia.org/wiki/Magura_Cave",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Magura_cave_023.jpg/1400px-Magura_cave_023.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-8000",
    "name": "Counting Tokens",
    "theme": "Language",
    "dates": "8000-7000 BCE (Neolithic)",
    "location": "Tapa Raza, south-east of modern Sulaimaniya Governorate, Iraq",
    "description": "Clay Developed for \"Concrete\" Counting",
    "src1": "https://www.historyofinformation.com/index.php#entry_5",
    "src2": "",
    "image1src": "https://historyofinformation.com/images/Simple-Tokens.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-7300",
    "name": "The Cuevas de las Manos Santa",
    "theme": "Language",
    "dates": "7,300 BC to 700 AD",
    "location": "Argentina",
    "description": "Believed to include the oldest-known cave paintings in South America.",
    "src1": "https://en.wikipedia.org/wiki/Cueva_de_las_Manos#Artwork",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/SantaCruz-CuevaManos-P2210651b.jpg/1024px-SantaCruz-CuevaManos-P2210651b.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-6000",
    "name": "Jiahu symbols",
    "theme": "Language",
    "dates": "~6000 BC",
    "location": "China",
    "description": "Possibly the Earliest Attempt at Writing",
    "src1": "https://www.historyofinformation.com/index.php#entry_1281",
    "src2": "https://thestrangecontinent.com/jiahu-symbols/",
    "image1src": "https://i0.wp.com/thestrangecontinent.com/wp-content/uploads/2019/05/Jiahu-symbols.jpg?ssl=1",
    "image1": "",
    "image2src": "https://historyofinformation.com/images/Screen_Shot_2019-08-27_at_12.48.16_PM.png",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-6000",
    "name": "Grotta dei Cervi",
    "theme": "Language",
    "dates": "~6000 BC",
    "location": "Southern Italy",
    "description": "Considered the most significant works of art of the European Post-Paleolithic era.",
    "src1": "https://en.wikipedia.org/wiki/Deer_Cave_(Otranto)",
    "src2": "",
    "image1src": "https://sp-ao.shortpixel.ai/client/to_auto,q_lossy,ret_img/https://www.cortedelsalento.net/wp-content/uploads/2016/02/images_grotta-dei-cervi-porto-badisco.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-4000",
    "name": "Globular envelope",
    "theme": "Money",
    "dates": "4000-3100 B.C.E",
    "location": "Iraq",
    "description": "(known as a Bulla) with a cluster of accountancy tokens, Uruk period",
    "src1": "https://en.wikipedia.org/wiki/History_of_accounting",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Accountancy_clay_envelope_Louvre_Sb1932.jpg/264px-Accountancy_clay_envelope_Louvre_Sb1932.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-3500",
    "name": "The Kish tablet",
    "theme": "Language",
    "dates": "3500 BCE",
    "location": "Sumer",
    "description": "Pictographic writing. Maybe the earliest known writing,",
    "src1": "https://en.wikipedia.org/wiki/Kish_tablet",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/a/a9/Tableta_con_trillo.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-3320",
    "name": "The Earliest Known Egyptian Writing",
    "theme": "Language",
    "dates": "Circa 3320 to 3150 BCE",
    "location": "Egypt",
    "description": "Bone and ivory tags, pottery vessels, and clay seal impressions bearing hieroglyphs unearthed at AbydosOffsite Link, one of the most ancient cities of Upper Egypt, 300 miles south of Cairo, have been dated between 3320 and 3150 BCE, making them the oldest known examples of Egyptian writing.",
    "src1": "https://www.historyofinformation.com/detail.php?entryid=3883",
    "src2": "",
    "image1src": "https://historyofinformation.com/images/3883a%20Large.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-3200",
    "name": "Economical tablet in Proto-Elamite script,",
    "theme": "Money",
    "dates": "3200 BCE to 2700 BCE",
    "location": "Current Iran",
    "description": "Proto-Elamite script in clay, Susa, Uruk period",
    "src1": "https://en.wikipedia.org/wiki/Susa",
    "src2": "https://humanjourney.us/the-changing-world-economy-section/debt-trust-and-money/",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/P1180316_Louvre_Suse_III_tablette_%C3%A9conomique_Sb15200_rwk.jpg/640px-P1180316_Louvre_Suse_III_tablette_%C3%A9conomique_Sb15200_rwk.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-3130",
    "name": "Ljubljana Marshes Wheel",
    "theme": "Technology",
    "dates": "3,130 BCE",
    "location": "Slovenia",
    "description": "Oldest wooden wheel yet discovered dating to Copper Age",
    "src1": "https://en.wikipedia.org/wiki/Ljubljana_Marshes_Wheel",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Ljubljana_Marshes_Wheel_with_axle_%28oldest_wooden_wheel_yet_discovered%29.jpg/2560px-Ljubljana_Marshes_Wheel_with_axle_%28oldest_wooden_wheel_yet_discovered%29.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-3100",
    "name": "Impressed tablet from Godin Tepe",
    "theme": "Money",
    "dates": "3100 BC",
    "location": "Current Iran",
    "description": "Tokens represent the first stage in the 9000-year continuous Near Eastern tradition of data processing. They led to writing. The change in communication that occurred on envelopes when the three-dimensional tokens were replaced by their two-dimensional impressions is considered the beginning of writing. (fig.3) Clay tablets bearing impressed signs replaced the tokens enclosed in envelopes. (fig.4) In turn, the impressed markings were followed by pictographs, or sketches of tokens and other items traced with a stylus.",
    "src1": "https://sites.utexas.edu/dsb/tokens/tokens/",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-3100",
    "name": "Stonehenge",
    "theme": "Language",
    "dates": "3100 BC to 2000 BC",
    "location": "England",
    "description": "Prehistoric monument consisting of an outer ring of vertical sarsen standing stones, each around 13 feet (4.0 m) high, seven feet (2.1 m) wide, and weighing around 25 tons, topped by connecting horizontal lintel stones.",
    "src1": "https://en.wikipedia.org/wiki/Stonehenge",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2007_07_30.jpg/440px-Stonehenge2007_07_30.jpg",
    "image1": "",
    "image2src": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Stonehenge_plan.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "-2600",
    "name": "First Securely Datable Mathematical Table",
    "theme": "Language",
    "dates": "2600 BCE",
    "location": "Iraq, Al-Qādisiyyah Governorate",
    "description": "The world’s oldest datable mathematical table, from Shuruppag, c. 2600 BCE.  The first two columns contain identical lengths in descending order from 600 to 60 rods (c. 3600–360 m) and the final column contains the square area of their product.",
    "src1": "https://www.historyofinformation.com/detail.php?id=1359",
    "src2": "",
    "image1src": "https://historyofinformation.com/images/1663a%20Large.jpg",
    "image1": "",
    "image2src": "https://historyofinformation.com/images/1663b%20Large.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2500",
    "name": "Silver ring and coil money",
    "theme": "Money",
    "dates": "c. 2,500 B.C.",
    "location": "Sumer",
    "description": "Note the standard size of cross-sections. Many of the pieces had a standard weight, ranging from one-twelfth of a shekel to sixty shekels. To assay a ring or coil, it could be weighed and cut at random locations. (Courtesy Oriental Institute, University of Chicago)",
    "src1": "https://nakamotoinstitute.org/shelling-out/",
    "src2": "",
    "image1src": "https://nakamotoinstitute.org/static/img/docs/shelling-out/coilcash.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2291",
    "name": "The Earliest Printing",
    "theme": "Technology",
    "dates": "Circa 2291 to 2254 BCE",
    "location": "Mesopotamia",
    "description": "Stamped into Soft Clay",
    "src1": "https://www.historyofinformation.com/detail.php?id=2241",
    "src2": "",
    "image1src": "https://historyofinformation.com/images/royal-inscription-of-naram-sin-ms-5106_f.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2200",
    "name": "First Iron",
    "theme": "Technology",
    "dates": "2200–2000 BCE.",
    "location": "Turkey",
    "description": "The earliest evidence for iron-making is a small number of iron fragments with the appropriate amounts of carbon admixture found in the Proto-Hittite layers at Kaman-Kalehöyük.",
    "src1": "https://en.wikipedia.org/wiki/Smelting#Early_iron_smelting",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-2000",
    "name": "Phaistos Disc",
    "theme": "Language",
    "dates": "middle or late Minoan Bronze Age (second millennium BC)",
    "location": "Phaistos, Crete",
    "description": "Attempted decipherments assume that it is; most additionally assume a syllabary, others an alphabet or logography. Attempts at decipherment are generally thought to be unlikely to succeed unless more examples of the signs are found, as it is generally agreed that there is not enough context available for a meaningful analysis.",
    "src1": "https://en.wikipedia.org/wiki/Phaistos_Disc",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/%CE%94%CE%AF%CF%83%CE%BA%CE%BF%CF%82_%CF%84%CE%B7%CF%82_%CE%A6%CE%B1%CE%B9%CF%83%CF%84%CE%BF%CF%8D_%CF%80%CE%BB%CE%B5%CF%85%CF%81%CE%AC_%CE%91_6380.JPG/1024px-%CE%94%CE%AF%CF%83%CE%BA%CE%BF%CF%82_%CF%84%CE%B7%CF%82_%CE%A6%CE%B1%CE%B9%CF%83%CF%84%CE%BF%CF%8D_%CF%80%CE%BB%CE%B5%CF%85%CF%81%CE%AC_%CE%91_6380.JPG",
    "image1": "",
    "image2src": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Discos_Phaitos_Umzeichnung.png",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-1800",
    "name": "Dynastic list",
    "theme": "Language",
    "dates": "1800–1600 BCE,",
    "location": "Susa",
    "description": "Twelve kings of Awan dynasty and twelve kings of the Shimashki Dynasty,",
    "src1": "https://en.wikipedia.org/wiki/Shimashki_Dynasty",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Dynastic_list_Awan_Siwashi_Louvre_Sb17729.jpg/384px-Dynastic_list_Awan_Siwashi_Louvre_Sb17729.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-1750",
    "name": "Code of Hammurab",
    "theme": "Language, Fiat",
    "dates": "1755–1750 BC",
    "location": "",
    "description": "The Code of Hammurabi was one of the earliest and most complete written legal codes and was proclaimed by the Babylonian king Hammurabi, who reigned from 1792 to 1750 B.C. Hammurabi expanded the city-state of Babylon along the Euphrates River to unite all of southern Mesopotamia. The Hammurabi code of laws, a collection of 282 rules, established standards for commercial interactions and set fines and punishments to meet the requirements of justice. Hammurabi’s Code was carved onto a massive, finger-shaped black stone stele (pillar) that was looted by invaders and finally rediscovered in 1901.",
    "src1": "https://www.history.com/topics/ancient-history/hammurabi",
    "src2": "https://en.wikipedia.org/wiki/Code_of_Hammurabi",
    "image1src": "https://www.history.com/.image/ar_233:100%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_3840/MTU3ODc5MDgzNzUxNjQ2OTQz/diorite-stela-with-the-code-of-hammurabi-2.jpg",
    "image1": "",
    "image2src": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/P1050763_Louvre_code_Hammurabi_face_rwk.JPG/466px-P1050763_Louvre_code_Hammurabi_face_rwk.JPG",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-1580",
    "name": "Gold cowries",
    "theme": "Money",
    "dates": "1580–1200 B.C.",
    "location": "Egypt",
    "description": "Adopting the fom older forms of money with gold as the base material ?",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/04-money-simplifies-trade/gold-cowries",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/04-money-simplifies-trade/01a.jpg",
    "image1": "",
    "image2src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/04-money-simplifies-trade/01b.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-1580",
    "name": "Gold dog",
    "theme": "Money",
    "dates": "1500–1000 B.C.",
    "location": "Peru (Inca)",
    "description": "",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/04-money-simplifies-trade/gold-dog",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/04-money-simplifies-trade/02.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-1280",
    "name": "Assyrian gold tablet",
    "theme": "Language",
    "dates": "3300 years ago",
    "location": "Current Iran",
    "description": "Assyrian gold tablet carved about 3300 years ago, found below the Temple of Ishtar in Assyria, Iraq. This 1-inch cuneiform inscription describes its construction and honors the Assyrian king Tukulti-Ninurta.",
    "src1": "https://www.atour.com/forums/history/27.html",
    "src2": "",
    "image1src": "https://www.atour.com/media/files/forums/20110407AIM091830.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-1100",
    "name": "First Smelting of Iron",
    "theme": "Technology",
    "dates": "ca. 1100–750 BCE",
    "location": "Egypt",
    "description": "Archaeologists have found indications of iron working in Ancient Egypt, somewhere between the Third Intermediate Period and 23rd Dynasty",
    "src1": "https://en.wikipedia.org/wiki/Smelting#Early_iron_smelting",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-700",
    "name": "Greek drachma of Aegina",
    "theme": "Money",
    "dates": "700–550 BC.",
    "location": "Greece",
    "description": "Obverse: Land Chelone / Reverse: ΑΙΓ(INA) and dolphin. The oldest Aegina chelone coins depicted sea turtles and were minted ca. 700–550 BC.",
    "src1": "https://en.wikipedia.org/wiki/Greek_drachma",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/4/46/BMC_193.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-625",
    "name": "Lydian Electrum Coin",
    "theme": "Money",
    "dates": "600-625 BCE",
    "location": "Modern-day Turkey",
    "description": "The ancient kingdom of Lydia, located in the western part of Anatolia in modern-day Turkey, is considered to be the origin of the first gold coins. Initially, the metal used was the naturally occurring electrum found in river beds and consisting of approximately 80-90% gold and 10-20% silver. However, the early Lydian coins had a much lower gold content, of around 55%, suggesting that the Lydian metallurgists were able to separate silver from electrum and then add extra silver to the coinage alloy before casting the coins.\nThe earliest coins, like these shown above, date from the late seventh century BCE, i.e., 600-625 BCE. The only markings consist of the punch marks on one side. By the middle of the sixth century BCE, the Lydians were producing pure gold coins such as the renowned Croesus Stater with a design on one side and punch marks on the other.",
    "src1": "https://www.lbma.org.uk/wonders-of-gold/items/lydian-electrum-coin",
    "src2": "",
    "image1src": "https://cdn.lbma.org.uk/items/Lydian-Electrum-Coin.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "-610",
    "name": "Electrum stater",
    "theme": "Money",
    "dates": "610–561 B.C.",
    "location": "Lydia (Turkey)",
    "description": "A group of seafaring people called the Lydians were the first in the Western World to make coins. King Alyattes standardized the weight and design of coins. The Lydian unit of weight was the stater, and this coin, produced during his reign, has the \"denomination\" of 1/3 stater. It is made of electrum, a natural alloy of gold and silver.",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/06-early-coins/electrum-stater.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/06-early-coins/04a.jpg",
    "image1": "",
    "image2src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/06-early-coins/04b.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-600",
    "name": "Chi tao",
    "theme": "Money",
    "dates": "600 and 200 B.C.",
    "location": "China",
    "description": "Ancient Qi State Knife Money Spring And Autumn Period",
    "src1": "https://en.wikipedia.org/wiki/Knife_money",
    "src2": "",
    "image1src": "https://image.invaluable.com/housePhotos/888Auctions/54/625154/H4602-L143371383.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-600",
    "name": "The Croesus Stater",
    "theme": "Money",
    "dates": "6th century BCE",
    "location": "Modern-day Turkey",
    "description": "The Croesus Stater, produced in Lydia (modern-day Turkey) in the middle of the sixth century BCE, was the world's first minted gold coin. It featured as Episode 25 of the BBC's landmark series \"A History of the World in 100 Objects\" in which the director of the British Museum, Neil MacGregor, described the historical and economic importance of the coin.",
    "src1": "https://www.lbma.org.uk/wonders-of-gold/items/croesus-stater",
    "src2": "",
    "image1src": "https://cdn.lbma.org.uk/items/_goldItemFeature/lbma-wonders-of-gold_Croesus_stater_Goldkammer.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "-560",
    "name": "Gold stater",
    "theme": "Money",
    "dates": "560–546 B.C.",
    "location": "Lydia (Turkey)",
    "description": "The mix of gold and silver in the electrum stater made value inconsistent. King Croesus, successor to Alyattes, stabilized the stater by minting one of pure gold. The Lydian government’s endorsement of its weight and quality made it widely acceptable and very useful in simplifying trade.",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/06-early-coins/gold-stater.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/06-early-coins/05a.jpg",
    "image1": "",
    "image2src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/06-early-coins/05b.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-545",
    "name": "The earliest coinage of Athens",
    "theme": "Money",
    "dates": "circa 545–525/515 BC",
    "location": "Greece",
    "description": "",
    "src1": "https://en.wikipedia.org/wiki/Ancient_Greek_coinage",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/c/cd/ATTICA%2C_Athens._Circa_545-525-15_BC.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-545",
    "name": "Athenian silver didrachm",
    "theme": "Money",
    "dates": "545–510 BC.",
    "location": "Greece",
    "description": "Heraldic type\" from the time of Peisistratos, 545–510 BC. Obverse: Four-spoked wheel. Reverse: Incuse square, divided diagonally.",
    "src1": "https://en.wikipedia.org/wiki/Greek_drachma",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/c/c7/Athens_545-510_BC_Didrachm.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-510",
    "name": "Archaic coin of Athens",
    "theme": "Money",
    "dates": "Circa 510–500/490 BC",
    "location": "Greece",
    "description": "With effigy of Athena on the obverse, and olive sprig, owl and αθε, initials of \"Athens\" on the reverse. Circa 510–500/490 BC",
    "src1": "https://en.wikipedia.org/wiki/Ancient_Greek_coinage",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/5/5f/ATTICA%2C_Athens._Circa_510_to_500-490_BC.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-500",
    "name": "Lady Aigai, Wife of Amyntas I, king of Macedon Tomb",
    "theme": "Money",
    "dates": "5th Century B.C.,,.",
    "location": "Greece",
    "description": "Probably the wife of Amyntas I, king of Macedon. 5th Century B.C., Aigai, Greece.  \n\nΒuried with a gold mask over her face, gold earrings, a headband over her hair and a necklace of gold beads. Her dress was fastened with silver pins, terminating in gold orbs in the shape of poppy capsules. Rosettes and other gold ornaments were sewn on various places of her dress. Also buried with her were a large number of clay figurines, a silver phiale and bronze vessels.",
    "src1": "https://www.greecehighdefinition.com/blog/2019/5/2/ancient-macedonia-the-lady-of-aigai-comes-to-light-treasures-from-an-epic-era-of-hellenism",
    "src2": "",
    "image1src": "https://images.squarespace-cdn.com/content/v1/57125c2c2b8dde54a34b537f/1556792474183-OY4WTO5AT181GW29W86B/GrCjTAUeQVyDTgfLycXUXU8sM-YJhRzGWlO_tZisldI.jpg?format=2500w",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-500",
    "name": "Amyntas I Coinage",
    "theme": "Money",
    "dates": "510-480 BC",
    "location": "Greece",
    "description": "Coinage towards the end of the reign of Amyntas I, under the Achaemenids, Aegae, circa 510-480 BC. Goat kneeling right, head reverted; pellet above and before / Quadripartite incuse square.",
    "src1": "https://en.wikipedia.org/wiki/Amyntas_I_of_Macedon",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/6/65/MACEDON%2C_Aegae._Circa_510-480_BC.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-500",
    "name": "Scytale (replica)",
    "theme": "Technology",
    "dates": "Around 5th BC",
    "location": "Greece (Sparta)",
    "description": "In cryptography, a scytale is a tool used to perform a transposition cipher, consisting of a cylinder with a strip of parchment wound around it on which is written a message. The ancient Greeks, and the Spartans in particular, are said to have used this cipher to communicate during military campaigns.",
    "src1": "https://en.wikipedia.org/wiki/Scytale",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/5/51/Skytale.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-478",
    "name": "Maya Mural Depicts Salt Trade",
    "theme": "Money",
    "dates": "2,500 years old",
    "location": "Mexico",
    "description": "According to a statement released by Louisiana State University, a 2,500-year-old mural at Calakmul, a Maya site located on Mexico’s Yucatan Peninsula, is the oldest-known record of salt being sold in a Maya marketplace. A person thought to be a salt vendor is shown holding what may be a salt cake wrapped in leaves, while a second person holds a spoon over a basket thought to be filled with granular salt.",
    "src1": "https://www.archaeology.org/news/9549-210324-maya-salt-vendor",
    "src2": "",
    "image1src": "https://www.archaeology.org/images/News/2103/Mexico-Calakmul-Mural.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-400",
    "name": "Earliest known currency from Jerusalem",
    "theme": "Money",
    "dates": "4th century BCE",
    "location": "Jerusalem",
    "description": "Among the earliest known currency from the area, including what the museum has identified as the world’s oldest Jewish coin.\nThe coins, dated to the 5th and 4th centuries BCE when the region was controlled by the Persian Empire, constitute “the largest collection in the world of Persian-period coins.” The collection includes a number of previously unknown varieties, the museum said. Chief among the rare artifacts is a silver drachm, an ancient coin based upon the Greek drachma, which, in clearly legible Aramaic script, bears the word yehud, or Judea.",
    "src1": "https://www.timesofisrael.com/israel-museum-obtains-worlds-first-jewish-coin/",
    "src2": "",
    "image1src": "https://static.timesofisrael.com/www/uploads/2013/12/YHD-drachm-both-sides.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-361",
    "name": "Persian Empire, Satrapy of Cilicia, Mazaios, Stater",
    "theme": "Money",
    "dates": "ca. 361-334 v. Chr.",
    "location": "Persian Empire",
    "description": "The spread of Greek-style coinage shows many interesting features of cultural admixture. At Tarsus, for instance, several Persian satraps during the 4th century minted coins for their military expenses. One of them was Mazaios (361-334 BC), the minting prerogative of this stater. While on Greek coins Zeus sits on the obverse, it is the god of fertility Baal Tars on this stater. This is suggested by the Aramaic legend \"baal tarz\" (Baal of Tarsos). The vine and the corn also allude to a vegetation deity. The eagle, on the other hand, is a typical attribute of Zeus. The reverse depicts a lion slaying a bull. This motif went back to an astrological symbolism and was common in Persian art.",
    "src1": "https://www.moneymuseum.com/en/coins?&id=671",
    "src2": "",
    "image1src": "https://touchcoins.moneymuseum.com/coins_media/Persian-Empire-Satrapy-of-Cilicia-Mazaios-Stater/671/obverse.png",
    "image1": "",
    "image2src": "https://touchcoins.moneymuseum.com/coins_media/Persian-Empire-Satrapy-of-Cilicia-Mazaios-Stater/671/reverse.png",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "-350",
    "name": "Sound money defined as: Durable, Transferrable, Divisible, Intrinsically Valuable",
    "theme": "Money",
    "dates": "~350 BCE",
    "location": "Greece",
    "description": "Aristotle (384 B.C.- 322 B.C.)",
    "src1": "https://www.marketoracle.co.uk/Article10370.html",
    "src2": "https://www.jstor.org/stable/4182455",
    "image1src": "https://www.worldhistoryedu.com/wp-content/uploads/2019/05/Aristotles-Life-and-History.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "474",
    "name": "Soapstone jar with 300 gold coins",
    "theme": "Money",
    "dates": "474 AD",
    "location": "",
    "description": "Archaeologists are studying a valuable trove of old Roman coins found on the site of a former theater in northern Italy.\nThe coins, at least 300 of them, date back to the late Roman imperial era and were found in a soapstone jar unearthed in the basement of the Cressoni Theater in Como, north of Milan.",
    "src1": "https://edition.cnn.com/style/article/roman-gold-coins-italy-cressoni-theater-trnd/index.html",
    "src2": "",
    "image1src": "https://dynaimage.cdn.cnn.com/cnn/q_auto,w_1183,c_fill,g_auto,h_665,ar_16:9/http%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F180910100856-03-roman-gold-coins.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "1199",
    "name": "",
    "theme": "",
    "dates": "",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "1200",
    "name": "Tally sticks",
    "theme": "Money",
    "dates": "Thirteenth century",
    "location": "United Kingdom",
    "description": "Tally sticks were a form of receipt for government income, which originated in the middle ages. However, their use is described much earlier by Pliny the Elder (AD 23-79), and were also found to be made from bone in the Upper Palaeolithic period (40-10,000 years ago). Wooden sticks were used in the middle ages and notches were cut (‘talea’ in Latin) indicating a sum owed to the Exchequer by sheriffs and other officials due to collect taxes and other money for the crown, and details written down each side. The stick was then sliced in two with the debtor being given the larger part (the foil) and the Exchequer keeping the smaller (known as the counterfoil). When the debt was repaid to the Exchequer, the two unique parts were married up to prove that the sum had been handed over.",
    "src1": "https://thebookandpapergathering.org/2011/03/11/the-conservation-and-preservation-of-wooden-tally-sticks/",
    "src2": "https://en.wikipedia.org/wiki/Tally_stick",
    "image1src": "https://bookandpapergroupgathering.files.wordpress.com/2011/03/figure-1.png",
    "image1": "",
    "image2src": "https://upload.wikimedia.org/wikipedia/commons/1/17/Medieval_tally_sticks.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "1201",
    "name": "",
    "theme": "",
    "dates": "",
    "location": "",
    "description": "",
    "src1": "",
    "src2": "",
    "image1src": "",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "60.8",
    "date_coord": "1740",
    "name": "Yap Stones",
    "theme": "Money",
    "dates": "1740–1940",
    "location": "Island of Yap",
    "description": "Yap stones were symbols of wealth.\nOn the island of Yap, stones like these were displayed in front of homes and were sometimes twice as tall as an adult. This example may be 200 years old. Yap stones were in use until World War II.",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/yap-stones.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/07.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "1750",
    "name": "Jade coins",
    "theme": "Money",
    "dates": "circa A.D. 1750",
    "location": "China",
    "description": "Jade coins were used as temple offerings\nThe Chinese considered jade “the jewel of Heaven.” This intricately carved jade coin from circa A.D. 1750 is one of the most beautiful forms of money.",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/jade-coins.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/08.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "68",
    "date_coord": "1800",
    "name": "Silver Bar",
    "theme": "Money",
    "dates": "19th century",
    "location": "China",
    "description": "",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/silver-bar.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/09.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "1800",
    "name": "Zappozap",
    "theme": "Money",
    "dates": "19th century",
    "location": "African Congo",
    "description": "",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/zappozap.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/06.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "1800",
    "name": "Bronze Tempo Coin",
    "theme": "Money",
    "dates": "19th century",
    "location": "Japan",
    "description": "",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/bronze-tempo-coin.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/02.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "1804",
    "name": "1 Billion humans",
    "theme": "Environment",
    "dates": "1804",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "1826",
    "name": "Essay on the principle of population",
    "theme": "Language, Fiat",
    "dates": "1826",
    "location": "England",
    "description": "Malthus argued that two types of checks hold population within resource limits: positive checks, which raise the death rate; and preventive ones, which lower the birth rate. The positive checks include hunger, disease and war; the preventive checks: birth control, postponement of marriage and celibacy.",
    "src1": "https://en.wikipedia.org/wiki/Thomas_Robert_Malthus#An_Essay_on_the_Principle_of_Population",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Malthus_-_Essay_on_the_principle_of_population%2C_1826_-_5884843.tif/lossy-page1-576px-Malthus_-_Essay_on_the_principle_of_population%2C_1826_-_5884843.tif.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "1834",
    "name": "Houses of Lords and Commons fire",
    "theme": "Money",
    "dates": "16th of October 1834",
    "location": "United Kingdom",
    "description": "Burning of excess tallies in the furnaces under the House of Lords’ Chamber caused the fire which destroyed the old Houses of Parliament",
    "src1": "https://thebookandpapergathering.org/2011/03/11/the-conservation-and-preservation-of-wooden-tally-sticks/",
    "src2": "",
    "image1src": "https://assets3.parliament.uk/woa/woa-zoom-popup/woa-large/1667-1-h.tif",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "1839",
    "name": "Three-legged coin",
    "theme": "Money",
    "dates": "A.D. 1839",
    "location": "Isle of Man",
    "description": "",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/3-legged-coin.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/05.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "68",
    "date_coord": "1850",
    "name": "Shoe money",
    "theme": "Money",
    "dates": "A.D. 1850–1933",
    "location": "China",
    "description": "",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/shoe-money.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/10.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "50",
    "date_coord": "1875",
    "name": "Whale tooth",
    "theme": "Money",
    "dates": "A.D. 1875–1945",
    "location": "Fiji Islands",
    "description": "",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/whale-tooth.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/01.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "69",
    "date_coord": "1916",
    "name": "Velvet Mark, Silk Mark",
    "theme": "Money",
    "dates": "1916–30s",
    "location": "Germany",
    "description": "This German money (1916–30s) made of fabric was called \"notgeld,\" meaning \"emergency money.",
    "src1": "https://www.atlantafed.org/about/tours/story-of-money/05-money-takes-many-shapes/velvet-silk-mark.aspx",
    "src2": "",
    "image1src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/03.jpg",
    "image1": "",
    "image2src": "https://www.atlantafed.org/-/media/images/about/tours/story-of-money/05-money-takes-many-shapes/04.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "69",
    "date_coord": "1920.08",
    "name": "Ponzi surrenders to authorities",
    "theme": "Crisis",
    "dates": "August 12 1920",
    "location": "USA",
    "description": "Born and raised in Italy, he became known in the early 1920s as a swindler in North America for his money-making scheme. He promised clients a 50% profit within 45 days or 100% profit within 90 days, by buying discounted postal reply coupons in other countries and redeeming them at face value in the U.S. as a form of arbitrage.[1]: 1 [2] In reality, Ponzi was paying earlier investors using the investments of later investors. While this type of fraudulent investment scheme was not originally invented by Ponzi, it became so identified with him that it now is referred to as a \"Ponzi scheme\".",
    "src1": "https://cdnc.ucr.edu/?a=d&d=HT19200812.2.43&e=-------en--20--1--txt-txIN--------",
    "src2": "",
    "image1src": "https://d3v93rzqvnwm3k.cloudfront.net/photos/images/fa43fb36b3ac97af4f0189d243dfadbf_three_column.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "69",
    "date_coord": "1927",
    "name": "2 Billion humans",
    "theme": "Environment",
    "dates": "1927",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "69",
    "date_coord": "1933.04",
    "name": "Executive Order 6102",
    "theme": "Money, Fiat",
    "dates": "April 5, 1933",
    "location": "US",
    "description": "Executive order signed on April 5, 1933, by US President Franklin D. Roosevelt \"forbidding the hoarding of gold coin, gold bullion, and gold certificates within the continental United States.\" The executive order was made under the authority of the Trading with the Enemy Act of 1917, as amended by the Emergency Banking Act in March 1933.",
    "src1": "https://en.wikipedia.org/wiki/Executive_Order_6102",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/a/a1/Executive_Order_6102.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "69",
    "date_coord": "1945.08",
    "name": "Atomic bombing of Hiroshima and Nagasaki",
    "theme": "Crisis",
    "dates": "6 and 9 August 1945",
    "location": "Japan, US",
    "description": "The United States detonated two atomic bombs over the Japanese cities of Hiroshima and Nagasaki on 6 and 9 August 1945, respectively. The two bombings killed between 129,000 and 226,000 people, most of whom were civilians, and remain the only use of nuclear weapons in armed conflict.",
    "src1": "https://en.wikipedia.org/wiki/Atomic_bombings_of_Hiroshima_and_Nagasaki",
    "src2": "https://nationalatomictestingmuseum.org/2022/06/08/spot-on-questions-and-answerers/",
    "image1src": "https://nationalatomictestingmuseum.org/wp-content/uploads/2022/06/bomb_next2.jpg",
    "image1": "",
    "image2src": "https://nationalatomictestingmuseum.org/wp-content/uploads/2022/06/measurements_cloud.jpg",
    "image2": "",
    "image3src": "https://nationalatomictestingmuseum.org/wp-content/uploads/2022/06/hiroshima.jpg",
    "image3": ""
  },
  {
    "left_shift": "69",
    "date_coord": "1960",
    "name": "3 Billion humans",
    "theme": "Environment",
    "dates": "1960",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "76",
    "date_coord": "1974",
    "name": "4 Billion humans",
    "theme": "Environment",
    "dates": "1974",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "77.5",
    "date_coord": "1987",
    "name": "5 Billion humans",
    "theme": "Environment",
    "dates": "1987",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "1994.01",
    "name": "CFA Franc overnight 50% devaluation.",
    "theme": "Money, Crisis",
    "dates": "12 January 1994",
    "location": "Central Africa",
    "description": "The CFA franc was created on 26 December 1945, along with the CFP franc. The reason for their creation was the weakness of the French franc immediately after World War II. When France ratified the Bretton Woods Agreement in December 1945, the French franc was devalued in order to set a fixed exchange rate with the US dollar.",
    "src1": "https://en.wikipedia.org/wiki/CFA_franc",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/CFA_Franc_map.svg/609px-CFA_Franc_map.svg.png",
    "image1": "",
    "image2src": "https://s.rfi.fr/media/display/1a4a4288-0d41-11ea-a937-005056bfe576/w:1280/p:16x9/000_PAR2004091513656_0.webp",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "80.5",
    "date_coord": "1998",
    "name": "6 Billion humans",
    "theme": "Environment",
    "dates": "1998",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "87",
    "date_coord": "2007.08",
    "name": "Ginko Financials",
    "theme": "Money, Crisis",
    "dates": "Aug 16th 2007",
    "location": "Linden Lab, US",
    "description": "Linden Acts of greater economic import include the banning of wagering on games of random chance or on real-life sporting events with L$. As soon as the rule change was announced, gaming regions were given a few days to close[citation needed]. Gaming region owners and game scripters either found other avenues of business or ceased operations. The fallout of this was the largest Linden Dollar bank in SL, Ginko Financial, which had its Linden Dollar ATMs in most major gaming regions, saw its reserves drained completely within hours, and was never able to catch up with Linden Dollar withdrawal requests, which eventually amounted to L$55 million out of deposits of L$180 million. Ginko's assets were primarily invested in either things of poor to no liquidity, or virtual securities that were then trading at significantly under their purchase price.",
    "src1": "https://www.economist.com/finance-and-economics/2007/08/16/trouble-in-paradise",
    "src2": "https://en.wikipedia.org/wiki/Economy_of_Second_Life",
    "image1src": "https://www.economist.com/img/b/1280/1048/90/sites/default/files/cf_images/20070818/3307FN2.jpg",
    "image1": "",
    "image2src": "http://alphavilleherald.com/images/2007-small/08/05/ginko_001.jpg",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "87.5",
    "date_coord": "2010",
    "name": "7 Billion humans",
    "theme": "Environment",
    "dates": "2010",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "88",
    "date_coord": "2012.11",
    "name": "Bitcoin Halving #1",
    "theme": "Money",
    "dates": "Nov. 28, 2012",
    "location": "",
    "description": "25 BTC per block. After a total of 10,500,000 BTC had been mined.",
    "src1": "",
    "src2": "",
    "image1src": "https://fs.bitcoinmagazine.com/img/images/bitcoin-miners-share-optimism-as-second-bitc.max-800x800.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "2013.01",
    "name": "First ASIC 130 nm chip",
    "theme": "Money",
    "dates": "January 19, 2013",
    "location": "China",
    "description": "60 GH/s for $1,299",
    "src1": "https://bitcoinmagazine.com/business/working-avalon-asic-confirmed-1359613230",
    "src2": "https://bitcoinmagazine.com/business/avalon-ships-bitcoins-first-consumer-asics-1358905223",
    "image1src": "https://bitcoinmagazine.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_320/MTc5Mjk3ODU0ODAwMDEyOTk1/working-avalon-asic-confirmed.webp",
    "image1": "",
    "image2src": "https://bitcoinmagazine.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_600/MTc5Mjk3NzYxMzg1MzI2Mjc1/avalon-ships-bitcoins-first-consumer-asics.webp",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "88",
    "date_coord": "2016.07",
    "name": "Bitcoin Halving #2",
    "theme": "Money",
    "dates": "July 9, 2016",
    "location": "",
    "description": "12.5 BTC per block.",
    "src1": "",
    "src2": "",
    "image1src": "https://fs.bitcoinmagazine.com/img/images/bitcoin-miners-share-optimism-as-second-bitc.max-800x800.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "88",
    "date_coord": "2019.05",
    "name": "Oculus Quest",
    "theme": "Technology",
    "dates": "May 21, 2019",
    "location": "US",
    "description": "In 2018 at Connect 5, it was announced that the new headset would be known as the Oculus Quest and would be priced at US$399. At F8 2019 it was announced that the Quest would ship on May 21, 2019. At launch, the device was priced at US$399 for the 64 GB version, and US$499 for the 128 GB version.",
    "src1": "https://en.wikipedia.org/wiki/Oculus_Quest#History",
    "src2": "",
    "image1src": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Oculus_Quest.jpeg/440px-Oculus_Quest.jpeg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "88",
    "date_coord": "2019.06",
    "name": "BitBox02",
    "theme": "Technology",
    "dates": "June 2019",
    "location": "Switzerland",
    "description": "The BitBox02 is easily concealed as well, but its sleek, compact and futuristic design (which includes a visible LCD screen) may give away its special nature. Compared to the Ledger, it’s harder to confuse with a USB flash drive (though, to ShiftCrypto’s merit, the BitBox has a male connector which is more faithful to the design of storage devices). For concealing purposes, the original BitBox01 is superior thanks to its basic design.",
    "src1": "https://bitcoinmagazine.com/reviews/bitcoin-wallet-reviews-whats-the-best-hardware-wallet-on-the-market",
    "src2": "https://twitter.com/_n1rna/status/1155923408133246981",
    "image1src": "https://bitcoinmagazine.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_1300/MTc5Mjk3ODUyMzc4NTIzMjg3/image-placeholder-title.webp",
    "image1": "",
    "image2src": "https://pbs.twimg.com/media/EAqqM_HX4AU1Y4F?format=jpg&name=medium",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "88",
    "date_coord": "2019.1",
    "name": "Coldcard Mk3",
    "theme": "Technology",
    "dates": "October 2019",
    "location": "Canada",
    "description": "The Coldcard can be used by itself without the need to connect to a computer. This means that you can use the Mk3 in an air gapped fashion, which can be a huge plus in the eyes of a security-driven bitcoin user. This is possible thanks to the microSD slot built into the side of the wallet — you can pass along transaction (and other) information to and from a computer by simply putting the chip into the computer and then back into the wallet. \nIn terms of security, the Mk3 uses Microchip's ATECC608A to store the critical master secret: the 24-word seed phrase for your BIP 32/BIP 39 wallet.",
    "src1": "https://mattodell.keybase.pub/coldcard.html",
    "src2": "https://bitcoinmagazine.com/reviews/video-review-coldcard-mk3",
    "image1src": "https://coldcardwallet.com/static/images/coldcard-mk3-onoff.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "88",
    "date_coord": "2020.04",
    "name": "Sparrow Wallet",
    "theme": "Technology",
    "dates": "12 Apr 2020",
    "location": "South Africa",
    "description": "Initial release \nTransaction editor only (no wallet)\nLoad PSBT files\nPaste transaction hex\nDetailed transaction inspection\nUpdate certain transaction fields (no Script editing)",
    "src1": "https://github.com/sparrowwallet/sparrow/releases/tag/v0.5",
    "src2": "",
    "image1src": "https://sparrowwallet.com/assets/images/control-your-sends.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "96",
    "date_coord": "2020.05",
    "name": "Bitcoin Halving #3",
    "theme": "Money",
    "dates": "May 11, 2020",
    "location": "",
    "description": "6.25 BTC per block.",
    "src1": "",
    "src2": "",
    "image1src": "https://fs.bitcoinmagazine.com/img/images/bitcoin-miners-share-optimism-as-second-bitc.max-800x800.jpg",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "99.1",
    "date_coord": "2021.06",
    "name": "El Salvador makes bitcoin legal tender",
    "theme": "Money, Fiat",
    "dates": "June 6, 2021",
    "location": "El salvador",
    "description": "In declaring bitcoin legal tender, El Salvador has become the first country to onboard to a non-fiat currency. Because bitcoin is issued programmatically and does not fall under the control of any third party or central bank, El Salvador is now uniquely positioned to take advantage of Bitcoin’s unique properties, particularly as a store of value that is provably scarce and natively digital.",
    "src1": "https://bitcoinmagazine.com/business/el-salvador-to-declare-bitcoin-as-legal-tender",
    "src2": "https://www.bbc.com/news/world-latin-america-57398274",
    "image1src": "https://preview.redd.it/2qzgwq3mk2471.png?width=891&format=png&auto=webp&s=8089e7c737932e03a49c4ebe0e6833f352b92845",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "",
    "date_coord": "2022.03",
    "name": "Argentine Congress Approves IMF Debt Deal That Would Discourage Crypto Usage",
    "theme": "Money, Fiat",
    "dates": "March 3, 2022",
    "location": "Argentina",
    "description": "The Argentine Senate on Thursday night approved a debt deal of $45 billion with the International Monetary Fund (IMF) linked to an agreement that includes a provision discouraging the use of cryptocurrencies.\n\nThe debt deal, also approved by the Chamber of Deputies on March 11, will serve to restructure a $57 billion program the country received in 2018.",
    "src1": "https://www.imf.org/-/media/files/publications/loi/2022/arg030322.ashx",
    "src2": "https://www.yahoo.com/now/argentine-congress-approves-imf-debt-062201906.html",
    "image1src": "assets/artifacts/argentina_imf.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "97",
    "date_coord": "2023",
    "name": "8 Billion humans",
    "theme": "Environment",
    "dates": "2023",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "98",
    "date_coord": "2037",
    "name": "9 Billion humans (projected)",
    "theme": "Environment",
    "dates": "2037",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  },
  {
    "left_shift": "98",
    "date_coord": "2058",
    "name": "10 Billion humans (projected)",
    "theme": "Environment",
    "dates": "2058",
    "location": "",
    "description": "",
    "src1": "https://populationconnection.org/blog/world-population-milestones-throughout-history/",
    "src2": "",
    "image1src": "https://populationconnection.org/wp-content/uploads/2022/07/1800-2100-1024x746.png",
    "image1": "",
    "image2src": "",
    "image2": "",
    "image3src": "",
    "image3": ""
  }
]
;
